export const DEFAULT_QUICK_NAV = {
  QuickNav1_Label: "Roles",
  QuickNav1_URL: "/directory/#/admin/people-permissions/roles",
  QuickNav2_Label: "People",
  QuickNav2_URL: "/directory/#/admin/directory/peopleV3",
  QuickNav3_Label: "Queues",
  QuickNav3_URL: "/directory/#/admin/admin/organization/_queuesV2",
  QuickNav4_Label: "Data Tables",
  QuickNav4_URL: "/directory/#/admin/routing/datatables",
  QuickNav5_Label: "Architect",
  QuickNav5_URL: "/architect/#/inboundcall/flows",
  QuickNav5_radio: "newTab",
  QuickNav6_Label: "API Explorer",
  QuickNav6_URL: "https://developer.genesys.cloud/devapps/api-explorer",
  QuickNav6_radio: "newTab",
};

export const FEATURE_MAP = {
  userList: "genesys-users",
  userRoles: "genesys-user-roles",
  exportRoles: "genesys-roles",
  phoneList: "genesys-phones",
  queueList: "genesys-queues",
  queueMemberList: "genesys-queue-members",
  exportSkills: "genesys-skills",
  exportGroups: "genesys-groups",
  exportGroupUsers: "genesys-group-members",
  exportPrompts: "genesys-prompts",
  bulkPhoneBuild: "genesys-bulk-phone-build",
  passwordReset: "genesys-bulk-password-reset",
  bulkAssignAutoAnswer: "genesys-bulk-auto-answer",
  bulkRoleAssign: "genesys-bulk-role-assign",
  bulkAssignSkills: "genesys-bulk-skill-assignment",
  bulkSelectUserLogoff: "genesys-bulk-logoff",
  masterAdmin: "genesys-create-master-admin",
  loadSchedules: "genesys-load-schedules",
  disconnect: "genesys-bulk-disconnect",
  callSpoof: "genesys-report-call-spoof",
  printConversationData: "genesys-report-conversation",
  goToInteraction: "genesys-report-interaction",
  goToFlowExecution: "genesys-report-flow",
  utterances: "genesys-report-utterances",
  intentHealth: "genesys-report-intent-health",
};

export const CONVERSATION_FEATURES = new Set([
  "printConversationData",
  "goToInteraction",
  "goToFlowExecution",
]);
